### ISSUE TITLE
How to reset CV

### ISSUE THREAD

**Issue by Bartusb** [robertklep/nefit-easy-commands#14]
Hi,

My NEFIT Central Heating system (CV) crashes with an error message now and then (“burner doen’t ignite”), so I need to reset the CV once every month manually. I do this via the rest button on the outside of the CV system itself.
I could not find an option in your software to send a reset command via the interface. I can still send other commands to the CV via your software..

Is there a way to reset the CV using your software and if not, could this be implemented?

Rgds,
Bart

**Comment by robertklep** [comment]
Hi Bart,

I don't have an Easy anymore so cannot check myself, but it looks like there's an endpoint that the app uses to reset the boiler.

Try this with the [CLI tool](https://github.com/robertklep/nefit-easy-cli):
```
easy --serial='SERIAL' --access-key='KEY' --password='PASSWORD' put /ecus/rrc/pm/reset '{"value":"true"}'
```
(replace `SERIAL`, `KEY` and `PASSWORD` with your credentials)

**Comment by Bartusb** [comment]
Thanks a lot for the quick response!
I tried the command, but get the following output:

easy --serial=xxxx --access-key=xxxx --password=xxxx put /ecus/rrc/pm/reset '{"value":"true"}'
Error: INVALID_RESPONSE
    at /usr/lib/node_modules/nefit-easy-cli/node_modules/nefit-easy-core/lib/index.js:247:23
    at tryCatcher (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21) {
  response: {
    protocolVersion: 'HTTP/1.0',
    statusCode: '400',
    statusMessage: 'Bad Request',
    headers: { 'Content-Type': 'application/json', connection: 'close' },
    body: ''
  }
}


After trying a more easy command like “status” or “location” the output looks good as expected.

Any suggestions?

Bart

**Comment by robertklep** [comment]
Instead of the Nefit Easy CLI tool, try the [`bosch-xmpp` CLI tool](https://github.com/robertklep/bosch-xmpp/):
```
bosch-xmpp --serial=xxxx --access-key=xxxx --password=xxxx nefit put /ecus/rrc/pm/reset '{"value":"true"}'
```

**Comment by Bartusb** [comment]
Hi Robert,

Thanks for trying to help out.

Installed the tool and while the following command:
bosch-xmpp --serial=Xxxxx --access-key=Xxxxx --password=Xxxxx nefit get /ecus/rrc/uiStatus
Returns:
{"id":"/ecus/rrc/uiStatus","type":"uiUpdate","recordable":0,"writeable":0,"value":{"CTD":"2021-05-12T17:26:47+01:00 We","CTR":"weather","UMD":"clock","MMT":"21.5","CPM":"auto","CSP":"19","TOR":"off","TOD":"0","TOT":"21.5","TSP":"21.5","IHT":"21.50","IHS":"ok","DAS":"off","TAS":"on","HMD":"off","ARS":"init","FPA":"off","ESI":"off","BAI":"No","BLE":"false","BBE":"false","BMR":"false","PMR":"false","RS":"off","DHW":"off","HED_EN":"false","HED_DEV":"false","FAH":"false","DOT":"false","HED_DB":""}}

The command :
bosch-xmpp --serial=Xxxxx --access-key=Xxxxx --password=Xxxxx nefit put /ecus/rrc/pm/reset '{"value":"true"}'

Returns:
Error: INVALID_RESPONSE
    at /usr/lib/node_modules/bosch-xmpp/lib/base-client.js:257:23
    at tryCatcher (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21) {
  response: {
    protocolVersion: 'HTTP/1.0',
    statusCode: '400',
    statusMessage: 'Bad Request',
    headers: { 'Content-Type': 'application/json', connection: 'close' },
    body: ''
  }
}

Looks like the “put /ecus/rrc/pm/reset ‘ {"value":"true"}’ is not understood.

Any ideas left?

Rgds,
Bart

**Comment by robertklep** [comment]
> Looks like the “put /ecus/rrc/pm/reset ‘ {"value":"true"}’ is not understood.

Well, it's understood, just not accepted by the thermostat. I don't know why that would be, but I've seen before that some endpoints are somehow protected. Perhaps, but I'm just guessing here, they can only be used locally over HTTP (however, I never tried to put the Easy in local mode, and HTTP isn't supported by the client anyway).

Perhaps it'll be easier to buy a cheap smart socket to reset the boiler.

**Comment by Bartusb** [comment]
Thanks Robert. Always good to see the open source world is cooperative in trying to help out.
Indeed I’ll use one of these cheap RF switches in parallel with the reset button.
Alternative is of course that I start to mentally accept the fact my CV is slowly (but surely) breaking down ;-)

Thanks again!
